### ISSUE TITLE
Add a sort command

### ISSUE THREAD

**Issue by ericsssan** [nus-cs2103-AY1617S1/addressbook-level1#503]
Add a sort command that can list the persons in alphabetical order.

**Comment by mauris** [comment]
hi @ericsssan, do follow the instructions to submit your pull requests.

**Comment by okkhoy** [comment]
@ericsssan please create a pull request indicating for the corresponding tutorial activity.
it is nice to see you getting used to the work flow creating a bug before implementing a feature! but at this moment it is unnecessary. 
closing the issue
